import type { CharId } from './types';

/**
 * Character bible: proportions + colors. Tweak here to restyle a character everywhere.
 * Units are pixels at scale 1 (scene is 1920x1080, floor around y=930).
 */
export type Design = {
  id: CharId;
  name: string;
  species: 'dog' | 'cat' | 'bunny';
  age: number;
  headR: number;
  eyeScale: number;
  torsoH: number;
  torsoTop: number; // shoulder width
  torsoBottom: number; // hip width
  legH: number;
  legW: number;
  armLen: number;
  armW: number;
  fur: { base: string; light: string; dark: string; muzzle: string; ear: string; stripe?: string };
  iris: string;
  irisDark: string;
  lashes: boolean;
  outfit: 'jacket' | 'sweater' | 'hoodie' | 'overalls';
  top: { base: string; dark: string; light: string };
  inner?: string; // tee under jacket / tee under overalls
  bottom: { base: string; dark: string; kind: 'jeans' | 'shorts' | 'overall-shorts' };
  shoes: { base: string; dark: string; sole: string };
  accent: string; // UI color for name tags / subtitles
  extras: Array<'backpack' | 'bow' | 'blush' | 'glasses' | 'bun'>;
};

export const DESIGNS: Record<CharId, Design> = {
  // Guests: Nico and Mati, Hija's classmates (they tease her, then apologize).
  nico: {
    id: 'nico',
    name: 'Nico',
    species: 'cat',
    age: 7,
    headR: 80,
    eyeScale: 1.12,
    torsoH: 96,
    torsoTop: 86,
    torsoBottom: 86,
    legH: 86,
    legW: 32,
    armLen: 98,
    armW: 28,
    fur: { base: '#9AA0A8', light: '#C4C9CF', dark: '#6B7178', muzzle: '#E9ECEF', ear: '#F2A7B5', stripe: '#6E747C' },
    iris: '#5FB85F',
    irisDark: '#2B6B2B',
    lashes: false,
    outfit: 'hoodie',
    top: { base: '#E03131', dark: '#B42323', light: '#FF6B6B' },
    bottom: { base: '#3B5BA5', dark: '#2A4380', kind: 'jeans' },
    shoes: { base: '#FFFFFF', dark: '#495057', sole: '#F1F3F5' },
    accent: '#C92A2A',
    extras: [],
  },
  mati: {
    id: 'mati',
    name: 'Mati',
    species: 'dog',
    age: 7,
    headR: 82,
    eyeScale: 1.12,
    torsoH: 98,
    torsoTop: 88,
    torsoBottom: 86,
    legH: 88,
    legW: 33,
    armLen: 100,
    armW: 29,
    fur: { base: '#7A4E2D', light: '#A0704A', dark: '#54331B', muzzle: '#E8C9A6', ear: '#4A2C17' },
    iris: '#8C5A2B',
    irisDark: '#3A240F',
    lashes: false,
    outfit: 'hoodie',
    top: { base: '#20C997', dark: '#0CA678', light: '#63E6BE' },
    bottom: { base: '#495057', dark: '#343A40', kind: 'shorts' },
    shoes: { base: '#FAB005', dark: '#E67700', sole: '#FFFFFF' },
    accent: '#0CA678',
    extras: [],
  },
  // Guest: the school teacher, a siamese cat with glasses.
  maestra: {
    id: 'maestra',
    name: 'Maestra',
    species: 'cat',
    age: 35,
    headR: 90,
    eyeScale: 1.0,
    torsoH: 166,
    torsoTop: 106,
    torsoBottom: 104,
    legH: 164,
    legW: 42,
    armLen: 158,
    armW: 34,
    fur: { base: '#F1E4D0', light: '#FFF6EA', dark: '#6B4F3A', muzzle: '#FFF6EA', ear: '#6B4F3A' },
    iris: '#4C9BE8',
    irisDark: '#1F4F85',
    lashes: true,
    outfit: 'sweater',
    top: { base: '#38B2AC', dark: '#2C8C87', light: '#6FD1CC' },
    bottom: { base: '#5C4B7D', dark: '#45385E', kind: 'jeans' },
    shoes: { base: '#6B4F3A', dark: '#4A3626', sole: '#F2EFE8' },
    accent: '#2C8C87',
    extras: ['glasses'],
  },
  // Guest: Tomi, a new classmate — a cream bunny who uses a wheelchair.
  tomi: {
    id: 'tomi',
    name: 'Tomi',
    species: 'bunny',
    age: 10,
    headR: 84,
    eyeScale: 1.15,
    torsoH: 112,
    torsoTop: 100,
    torsoBottom: 96,
    legH: 96,
    legW: 38,
    armLen: 112,
    armW: 32,
    fur: { base: '#EFE3D3', light: '#FFFFFF', dark: '#C8B59E', muzzle: '#FFFFFF', ear: '#F7B4C2' },
    iris: '#8B5E3C',
    irisDark: '#3E2614',
    lashes: false,
    outfit: 'hoodie',
    top: { base: '#FF922B', dark: '#E8590C', light: '#FFA94D' },
    bottom: { base: '#495057', dark: '#343A40', kind: 'jeans' },
    shoes: { base: '#FFFFFF', dark: '#E8590C', sole: '#F1F3F5' },
    accent: '#E8590C',
    extras: ['blush'],
  },
  // Guest: Benja, Hijo's classmate — a little beagle.
  benja: {
    id: 'benja',
    name: 'Benja',
    species: 'dog',
    age: 10,
    headR: 86,
    eyeScale: 1.15,
    torsoH: 112,
    torsoTop: 100,
    torsoBottom: 96,
    legH: 98,
    legW: 38,
    armLen: 112,
    armW: 32,
    fur: { base: '#C68A4B', light: '#E2B07A', dark: '#8A5A2B', muzzle: '#FFFFFF', ear: '#5C3A1E' },
    iris: '#6B4A2B',
    irisDark: '#2E1E10',
    lashes: false,
    outfit: 'hoodie',
    top: { base: '#40C057', dark: '#2F9E44', light: '#69DB7C' },
    bottom: { base: '#364FC7', dark: '#283593', kind: 'shorts' },
    shoes: { base: '#FA5252', dark: '#C92A2A', sole: '#FFFFFF' },
    accent: '#2F9E44',
    extras: ['blush'],
  },
  // Guests: Benja's dad and mom (beagles).
  benjaPapa: {
    id: 'benjaPapa',
    name: 'Papá de Benja',
    species: 'dog',
    age: 38,
    headR: 94,
    eyeScale: 1,
    torsoH: 175,
    torsoTop: 130,
    torsoBottom: 122,
    legH: 150,
    legW: 48,
    armLen: 166,
    armW: 39,
    fur: { base: '#B97F45', light: '#D9A673', dark: '#7D5129', muzzle: '#FFFFFF', ear: '#4E301A' },
    iris: '#5C4024',
    irisDark: '#2A1B0D',
    lashes: false,
    outfit: 'jacket',
    top: { base: '#3B5BDB', dark: '#2B44A8', light: '#5C7CFA' },
    inner: '#F8F9FA',
    bottom: { base: '#495057', dark: '#343A40', kind: 'jeans' },
    shoes: { base: '#343A40', dark: '#1E2124', sole: '#ADB5BD' },
    accent: '#3B5BDB',
    extras: [],
  },
  benjaMama: {
    id: 'benjaMama',
    name: 'Mamá de Benja',
    species: 'dog',
    age: 35,
    headR: 90,
    eyeScale: 1.05,
    torsoH: 168,
    torsoTop: 108,
    torsoBottom: 104,
    legH: 166,
    legW: 42,
    armLen: 160,
    armW: 34,
    fur: { base: '#D19A5E', light: '#EBC394', dark: '#94673A', muzzle: '#FFFFFF', ear: '#6B4423' },
    iris: '#3F8F5B',
    irisDark: '#1D4A2C',
    lashes: true,
    outfit: 'sweater',
    top: { base: '#FF8787', dark: '#E8605F', light: '#FFA8A8' },
    bottom: { base: '#748FFC', dark: '#5C7CFA', kind: 'jeans' },
    shoes: { base: '#F8F9FA', dark: '#868E96', sole: '#DEE2E6' },
    accent: '#E8605F',
    extras: [],
  },
  // Guest: Abuela, Papá's mom — a senior labrador with glasses and a bun.
  abuela: {
    id: 'abuela',
    name: 'Abuela',
    species: 'dog',
    age: 70,
    headR: 92,
    eyeScale: 0.95,
    torsoH: 160,
    torsoTop: 116,
    torsoBottom: 122,
    legH: 140,
    legW: 44,
    armLen: 154,
    armW: 36,
    fur: { base: '#E6C79A', light: '#F6E3C4', dark: '#B8956A', muzzle: '#FFF8EC', ear: '#CFAE80' },
    iris: '#7A4A1E',
    irisDark: '#3E220B',
    lashes: true,
    outfit: 'sweater',
    top: { base: '#AE3EC9', dark: '#862E9C', light: '#CC5DE8' },
    bottom: { base: '#5C5F66', dark: '#3D3F44', kind: 'jeans' },
    shoes: { base: '#8B5E3C', dark: '#5C3A1E', sole: '#C9A27A' },
    accent: '#AE3EC9',
    extras: ['glasses', 'bun'],
  },
  // Guest: Lola, Hija's best friend — a white kitten with round glasses and yellow overalls.
  lola: {
    id: 'lola',
    name: 'Lola',
    species: 'cat',
    age: 7,
    headR: 80,
    eyeScale: 1.15,
    torsoH: 94,
    torsoTop: 84,
    torsoBottom: 84,
    legH: 84,
    legW: 31,
    armLen: 96,
    armW: 27,
    fur: { base: '#F3EEE7', light: '#FFFFFF', dark: '#CFC5B8', muzzle: '#FFFFFF', ear: '#F7A9B8' },
    iris: '#7A5AF8',
    irisDark: '#3B2A8C',
    lashes: true,
    outfit: 'overalls',
    top: { base: '#FFD43B', dark: '#F2B705', light: '#FFE066' },
    inner: '#A5D8FF',
    bottom: { base: '#FFD43B', dark: '#F2B705', kind: 'overall-shorts' },
    shoes: { base: '#4DABF7', dark: '#1C7ED6', sole: '#FFFFFF' },
    accent: '#F59F00',
    extras: ['glasses', 'blush'],
  },
  // Guest: the family dentist, a friendly grey schnauzer in a white coat.
  dentista: {
    id: 'dentista',
    name: 'Dentista',
    species: 'dog',
    age: 45,
    headR: 94,
    eyeScale: 0.95,
    torsoH: 178,
    torsoTop: 128,
    torsoBottom: 124,
    legH: 150,
    legW: 48,
    armLen: 166,
    armW: 38,
    fur: { base: '#A9A6A2', light: '#D2CFCA', dark: '#77736E', muzzle: '#EEEBE6', ear: '#8D8984' },
    iris: '#5B7A99',
    irisDark: '#26394D',
    lashes: false,
    outfit: 'jacket',
    top: { base: '#F8F9FA', dark: '#CED4DA', light: '#FFFFFF' },
    inner: '#8CE0D2',
    bottom: { base: '#63C7B8', dark: '#3FA394', kind: 'jeans' },
    shoes: { base: '#F5F2EA', dark: '#5F6670', sole: '#E2DCCD' },
    accent: '#12B886',
    extras: ['glasses'],
  },
  papa: {
    id: 'papa',
    name: 'Max',
    species: 'dog',
    age: 36,
    headR: 96,
    eyeScale: 1,
    torsoH: 175,
    torsoTop: 132,
    torsoBottom: 122,
    legH: 150,
    legW: 50,
    armLen: 168,
    armW: 40,
    fur: { base: '#E9A945', light: '#F8CF83', dark: '#C1801F', muzzle: '#FCE6BC', ear: '#CF8A2E' },
    iris: '#7A4A1E',
    irisDark: '#3E220B',
    lashes: false,
    outfit: 'jacket',
    top: { base: '#55812F', dark: '#3C6120', light: '#73A045' },
    inner: '#F1E8D4',
    bottom: { base: '#2F4570', dark: '#22335A', kind: 'jeans' },
    shoes: { base: '#F5F2EA', dark: '#2E3140', sole: '#E2DCCD' },
    accent: '#2F6FD0',
    extras: [],
  },
  mama: {
    id: 'mama',
    name: 'Luna',
    species: 'cat',
    age: 32,
    headR: 90,
    eyeScale: 1.05,
    torsoH: 168,
    torsoTop: 108,
    torsoBottom: 104,
    legH: 168,
    legW: 42,
    armLen: 160,
    armW: 34,
    fur: { base: '#2C2A33', light: '#4A4656', dark: '#18171D', muzzle: '#3D3946', ear: '#EBA3AE' },
    iris: '#C2CC3A',
    irisDark: '#6D7A12',
    lashes: true,
    outfit: 'sweater',
    top: { base: '#B89DDD', dark: '#9479C3', light: '#D2BEEE' },
    bottom: { base: '#8DAED8', dark: '#6A8DBE', kind: 'jeans' },
    shoes: { base: '#2E2D38', dark: '#1B1A22', sole: '#F2EFE8' },
    accent: '#9B59C9',
    extras: [],
  },
  hijo: {
    id: 'hijo',
    name: 'Lio',
    species: 'dog',
    age: 10,
    headR: 88,
    eyeScale: 1.15,
    torsoH: 116,
    torsoTop: 104,
    torsoBottom: 98,
    legH: 100,
    legW: 40,
    armLen: 116,
    armW: 33,
    fur: { base: '#EFB24E', light: '#FBD58E', dark: '#C98A2A', muzzle: '#FDE9C4', ear: '#D59436' },
    iris: '#2C83C9',
    irisDark: '#123E6B',
    lashes: false,
    outfit: 'hoodie',
    top: { base: '#2F71D3', dark: '#1F55A8', light: '#5592EA' },
    bottom: { base: '#8C7D4D', dark: '#6F623A', kind: 'shorts' },
    shoes: { base: '#22355F', dark: '#16233F', sole: '#F2EFE8' },
    accent: '#2B8A3E',
    extras: ['backpack', 'blush'],
  },
  hija: {
    id: 'hija',
    name: 'Tini',
    species: 'cat',
    age: 7,
    headR: 82,
    eyeScale: 1.2,
    torsoH: 96,
    torsoTop: 86,
    torsoBottom: 86,
    legH: 86,
    legW: 32,
    armLen: 98,
    armW: 28,
    fur: { base: '#F39136', light: '#FFB868', dark: '#CF6C1C', muzzle: '#FFE6C8', ear: '#F7A9B8', stripe: '#D7681A' },
    iris: '#2FB3C4',
    irisDark: '#0F5E6B',
    lashes: true,
    outfit: 'overalls',
    top: { base: '#8C59CF', dark: '#6F41B1', light: '#A97BE3' },
    inner: '#F8BCD6',
    bottom: { base: '#8C59CF', dark: '#6F41B1', kind: 'overall-shorts' },
    shoes: { base: '#F2809F', dark: '#D65B7E', sole: '#FFFFFF' },
    accent: '#E8590C',
    extras: ['bow', 'blush'],
  },
};

/** Total height (feet to top of head) at scale 1, handy for placing props. */
export const heightOf = (id: CharId) => {
  const d = DESIGNS[id];
  return d.legH + d.torsoH + d.headR * 1.9;
};
